<form method="GET" action="{{ url()->current() }}" class="mb-7 rounded-sm border border-line-200 bg-white p-4 sm:p-5">
    <div class="grid gap-4 md:grid-cols-2 lg:grid-cols-[1.5fr_1fr_1fr_1fr_auto] lg:items-end">
        <div><label for="q" class="mb-1.5 block text-[11px] font-medium text-muted-600">البحث</label><input type="search" name="q" id="q" value="{{ request('q') }}" placeholder="اسم المنتج أو الحجر" class="min-h-10 w-full rounded-sm border border-line-200 bg-ivory-50 px-3 py-2 text-sm focus:border-lujain-700 focus:ring-2 focus:ring-lujain-700/10"></div>
        <div><label for="stone" class="mb-1.5 block text-[11px] font-medium text-muted-600">الحجر</label><select name="stone" id="stone" class="min-h-10 w-full rounded-sm border border-line-200 bg-ivory-50 px-3 py-2 text-sm focus:border-lujain-700 focus:ring-2 focus:ring-lujain-700/10"><option value="">كل الأحجار</option>@foreach ($stones as $stone)<option value="{{ $stone }}" @selected(request('stone') === $stone)>{{ $stone }}</option>@endforeach</select></div>
        <div><label for="availability" class="mb-1.5 block text-[11px] font-medium text-muted-600">التوفر</label><select name="availability" id="availability" class="min-h-10 w-full rounded-sm border border-line-200 bg-ivory-50 px-3 py-2 text-sm focus:border-lujain-700 focus:ring-2 focus:ring-lujain-700/10"><option value="">الكل</option><option value="available" @selected(request('availability') === 'available')>متوفر</option><option value="sold_out" @selected(request('availability') === 'sold_out')>نفدت الكمية</option></select></div>
        <div><label for="sort" class="mb-1.5 block text-[11px] font-medium text-muted-600">الترتيب</label><select name="sort" id="sort" class="min-h-10 w-full rounded-sm border border-line-200 bg-ivory-50 px-3 py-2 text-sm focus:border-lujain-700 focus:ring-2 focus:ring-lujain-700/10"><option value="newest" @selected(request('sort', 'newest') === 'newest')>الأحدث</option><option value="price_asc" @selected(request('sort') === 'price_asc')>السعر: الأقل</option><option value="price_desc" @selected(request('sort') === 'price_desc')>السعر: الأعلى</option></select></div>
        <button type="submit" class="min-h-10 rounded-sm bg-lujain-800 px-5 text-sm font-semibold text-white transition hover:bg-lujain-700">تطبيق</button>
    </div>
    @if (request()->hasAny(['q', 'stone', 'availability', 'sort']))<a href="{{ url()->current() }}" class="mt-3 inline-block text-xs text-lujain-700 underline underline-offset-4">إعادة ضبط التصفية</a>@endif
</form>
