@extends('layouts.admin')
@section('title', 'إعدادات المتجر')
@section('content')
<div class="mx-auto max-w-4xl space-y-6"><div><p class="eyebrow">التهيئة العامة</p><h1 class="mt-2 text-2xl font-semibold">إعدادات المتجر</h1><p class="mt-1 text-sm text-muted-600">بيانات التواصل والدفع والسياسات الظاهرة للعملاء.</p></div>@if (session('success'))<div class="alert-success">{{ session('success') }}</div>@endif @if ($errors->any())<div class="alert-error">@foreach ($errors->all() as $error)<p>{{ $error }}</p>@endforeach</div>@endif
<form method="POST" action="{{ route('admin.settings.update') }}" class="space-y-6">@csrf @method('PUT')
<section class="admin-card"><h2 class="mb-5 text-lg font-semibold">هوية المتجر والتواصل</h2><div class="grid gap-5 md:grid-cols-2"><div><label for="store_name_ar" class="field-label">اسم المتجر</label><input type="text" id="store_name_ar" name="store_name_ar" value="{{ old('store_name_ar', $setting->store_name_ar) }}" required></div><div><label for="phone" class="field-label">رقم الهاتف</label><input type="text" id="phone" name="phone" value="{{ old('phone', $setting->phone) }}" dir="ltr"></div><div><label for="whatsapp" class="field-label">رقم WhatsApp</label><input type="text" id="whatsapp" name="whatsapp" value="{{ old('whatsapp', $setting->whatsapp) }}" dir="ltr"></div><div><label for="instagram_url" class="field-label">رابط Instagram</label><input type="url" id="instagram_url" name="instagram_url" value="{{ old('instagram_url', $setting->instagram_url) }}" placeholder="https://instagram.com/..." dir="ltr"></div></div></section>
<section class="admin-card"><h2 class="mb-5 text-lg font-semibold">الدفع والحجوزات</h2><div class="grid gap-5 md:grid-cols-3"><div><label for="whish_number" class="field-label">رقم Whish Money</label><input type="text" id="whish_number" name="whish_number" value="{{ old('whish_number', $setting->whish_number) }}" dir="ltr"></div><div><label for="currency" class="field-label">العملة</label><input type="text" id="currency" name="currency" value="{{ old('currency', $setting->currency) }}" maxlength="3" dir="ltr" required></div><div><label for="reservation_hours" class="field-label">مدة الحجز بالساعات</label><input type="number" id="reservation_hours" name="reservation_hours" value="{{ old('reservation_hours', $setting->reservation_hours) }}" min="1" required></div></div></section>
<section class="admin-card"><h2 class="mb-5 text-lg font-semibold">المحتوى والسياسات</h2><div class="space-y-5"><div><label for="about_text_ar" class="field-label">نص «من نحن»</label><textarea id="about_text_ar" name="about_text_ar" rows="5">{{ old('about_text_ar', $setting->about_text_ar) }}</textarea></div><div><label for="policy_text_ar" class="field-label">سياسة المتجر</label><textarea id="policy_text_ar" name="policy_text_ar" rows="7">{{ old('policy_text_ar', $setting->policy_text_ar) }}</textarea></div></div></section><div class="flex justify-end"><button type="submit" class="btn-primary min-w-44">حفظ الإعدادات</button></div></form></div>
@endsection
